name: Publish to GitHub Packages

on:
  workflow_dispatch:
    inputs: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up .npmrc for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_PAT }}" > ~/.npmrc
          echo "@fneco:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
